from __future__ import annotations

PROJECTS = [
    {
        "id": 1,
        "identifier": "platform-core",
        "name": "Platform Core",
        "description": "Core platform services and authentication.",
        "status": 1,
        "is_public": True,
        "created_on": "2025-01-10T08:30:00Z",
        "updated_on": "2026-02-19T09:15:00Z",
    },
    {
        "id": 2,
        "identifier": "mobile-app",
        "name": "Mobile App",
        "description": "Mobile client issues and roadmap.",
        "status": 1,
        "is_public": True,
        "created_on": "2025-03-05T10:00:00Z",
        "updated_on": "2026-02-20T11:20:00Z",
    },
    {
        "id": 3,
        "identifier": "secret-lab",
        "name": "Secret Lab",
        "description": "Restricted experiments and pilots.",
        "status": 1,
        "is_public": False,
        "created_on": "2025-06-12T14:00:00Z",
        "updated_on": "2026-02-18T15:30:00Z",
    },
]

USERS = [
    {
        "id": 1,
        "login": "alice",
        "firstname": "Alice",
        "lastname": "Smith",
        "mail": "alice@example.test",
        "admin": True,
        "status": 1,
        "created_on": "2024-01-01T09:00:00Z",
        "updated_on": "2026-02-01T09:00:00Z",
    },
    {
        "id": 2,
        "login": "bob",
        "firstname": "Bob",
        "lastname": "Brown",
        "mail": "bob@example.test",
        "admin": False,
        "status": 1,
        "created_on": "2024-01-15T09:00:00Z",
        "updated_on": "2026-01-30T09:00:00Z",
    },
    {
        "id": 3,
        "login": "carol",
        "firstname": "Carol",
        "lastname": "Davis",
        "mail": "carol@example.test",
        "admin": False,
        "status": 1,
        "created_on": "2024-02-10T09:00:00Z",
        "updated_on": "2026-01-28T09:00:00Z",
    },
]

GROUPS = [
    {"id": 11, "name": "Backend Team", "user_ids": [1, 2]},
    {"id": 12, "name": "Mobile Team", "user_ids": [2, 3]},
]

TRACKERS = [
    {"id": 1, "name": "Bug", "default_status_id": 1, "description": "Defect"},
    {"id": 2, "name": "Feature", "default_status_id": 1, "description": "Feature request"},
    {"id": 3, "name": "Support", "default_status_id": 2, "description": "Support ticket"},
]

ISSUE_STATUSES = [
    {"id": 1, "name": "New", "is_closed": False, "is_default": True},
    {"id": 2, "name": "In Progress", "is_closed": False, "is_default": False},
    {"id": 3, "name": "Resolved", "is_closed": False, "is_default": False},
    {"id": 5, "name": "Closed", "is_closed": True, "is_default": False},
]

ISSUE_PRIORITIES = [
    {"id": 1, "name": "Low", "position": 1, "is_default": False, "active": True},
    {"id": 2, "name": "Normal", "position": 2, "is_default": True, "active": True},
    {"id": 3, "name": "High", "position": 3, "is_default": False, "active": True},
    {"id": 4, "name": "Urgent", "position": 4, "is_default": False, "active": True},
]

ISSUES = [
    {
        "id": 101,
        "project_id": 1,
        "tracker_id": 2,
        "status_id": 2,
        "priority_id": 3,
        "subject": "Unified login for admin panel",
        "description": "Implement SSO-based login for admin panel using OAuth2 + PKCE.",
        "author_id": 1,
        "assigned_to_id": 2,
        "start_date": "2026-01-04",
        "due_date": "2026-02-28",
        "done_ratio": 75,
        "is_private": False,
        "estimated_hours": 24.0,
        "spent_hours": 16.5,
        "created_on": "2026-01-04T10:00:00Z",
        "updated_on": "2026-02-16T11:15:00Z",
        "closed_on": None,
        "custom_fields": [
            {"id": 901, "name": "Module", "value": "Auth"},
            {"id": 902, "name": "Customer Impact", "value": "High"},
        ],
        "journals": [
            {
                "id": 1001,
                "user_id": 2,
                "notes": "Added OAuth scope mapping and fallback to local login.",
                "private_notes": False,
                "created_on": "2026-01-12T13:00:00Z",
                "details": [
                    {
                        "property": "attr",
                        "name": "status_id",
                        "old_value": "1",
                        "new_value": "2",
                    }
                ],
            },
            {
                "id": 1002,
                "user_id": 1,
                "notes": "Security review requested. Add token rotation evidence.",
                "private_notes": True,
                "created_on": "2026-02-10T09:30:00Z",
                "details": [],
            },
        ],
        "attachments": [
            {
                "id": 5001,
                "filename": "sso-sequence.md",
                "filesize": 33800,
                "content_type": "text/markdown",
                "description": "Sequence diagram for OAuth login flow",
                "content_url": "http://mock-redmine.local/attachments/5001/sso-sequence.md",
                "downloads": 12,
                "author_id": 2,
                "created_on": "2026-01-12T13:05:00Z",
                "digest": "d41d8cd98f00b204e9800998ecf8427e",
            }
        ],
        "relations": [
            {"id": 7001, "issue_id": 102, "relation_type": "blocks", "delay": None}
        ],
        "watcher_user_ids": [1, 3],
        "child_ids": [103],
    },
    {
        "id": 102,
        "project_id": 1,
        "tracker_id": 1,
        "status_id": 1,
        "priority_id": 4,
        "subject": "Login callback timeout in Safari",
        "description": "Safari occasionally times out on OAuth callback route.",
        "author_id": 3,
        "assigned_to_id": 2,
        "start_date": "2026-02-01",
        "due_date": "2026-02-21",
        "done_ratio": 25,
        "is_private": False,
        "estimated_hours": 8.0,
        "spent_hours": 2.0,
        "created_on": "2026-02-01T08:15:00Z",
        "updated_on": "2026-02-20T08:20:00Z",
        "closed_on": None,
        "custom_fields": [{"id": 901, "name": "Module", "value": "Auth"}],
        "journals": [
            {
                "id": 1003,
                "user_id": 2,
                "notes": "Reproduced on Safari 17.4, suspect cookie SameSite mismatch.",
                "private_notes": False,
                "created_on": "2026-02-02T11:00:00Z",
                "details": [],
            }
        ],
        "attachments": [],
        "relations": [{"id": 7002, "issue_id": 101, "relation_type": "blocked", "delay": None}],
        "watcher_user_ids": [1],
        "child_ids": [],
    },
    {
        "id": 103,
        "project_id": 1,
        "tracker_id": 3,
        "status_id": 3,
        "priority_id": 2,
        "subject": "Update runbook for OAuth rollback",
        "description": "Prepare rollback procedure for authentication incidents.",
        "author_id": 1,
        "assigned_to_id": 3,
        "start_date": "2026-02-03",
        "due_date": "2026-02-17",
        "done_ratio": 100,
        "is_private": False,
        "estimated_hours": 3.0,
        "spent_hours": 3.0,
        "created_on": "2026-02-03T09:00:00Z",
        "updated_on": "2026-02-15T18:00:00Z",
        "closed_on": "2026-02-15T18:00:00Z",
        "custom_fields": [{"id": 901, "name": "Module", "value": "Operations"}],
        "journals": [],
        "attachments": [],
        "relations": [],
        "watcher_user_ids": [2, 3],
        "child_ids": [],
    },
    {
        "id": 201,
        "project_id": 2,
        "tracker_id": 2,
        "status_id": 2,
        "priority_id": 2,
        "subject": "Offline mode sync strategy",
        "description": "Define queue behavior for mobile offline mode.",
        "author_id": 2,
        "assigned_to_id": 3,
        "start_date": "2026-01-20",
        "due_date": "2026-03-05",
        "done_ratio": 55,
        "is_private": False,
        "estimated_hours": 30.0,
        "spent_hours": 10.0,
        "created_on": "2026-01-20T10:30:00Z",
        "updated_on": "2026-02-19T09:45:00Z",
        "closed_on": None,
        "custom_fields": [{"id": 901, "name": "Module", "value": "Sync"}],
        "journals": [
            {
                "id": 2001,
                "user_id": 3,
                "notes": "Conflict resolution changed to server-wins for profile payload.",
                "private_notes": False,
                "created_on": "2026-02-11T12:20:00Z",
                "details": [],
            }
        ],
        "attachments": [],
        "relations": [],
        "watcher_user_ids": [2],
        "child_ids": [],
    },
    {
        "id": 301,
        "project_id": 3,
        "tracker_id": 2,
        "status_id": 1,
        "priority_id": 4,
        "subject": "Confidential pilot: biometric login",
        "description": "Evaluate biometric login workflow for enterprise pilot.",
        "author_id": 1,
        "assigned_to_id": 1,
        "start_date": "2026-02-01",
        "due_date": "2026-03-15",
        "done_ratio": 20,
        "is_private": True,
        "estimated_hours": 40.0,
        "spent_hours": 6.0,
        "created_on": "2026-02-01T09:00:00Z",
        "updated_on": "2026-02-18T10:10:00Z",
        "closed_on": None,
        "custom_fields": [{"id": 903, "name": "Confidentiality", "value": "Internal"}],
        "journals": [
            {
                "id": 3001,
                "user_id": 1,
                "notes": "Pilot participant list uploaded in secure vault.",
                "private_notes": True,
                "created_on": "2026-02-10T15:00:00Z",
                "details": [],
            }
        ],
        "attachments": [],
        "relations": [],
        "watcher_user_ids": [1],
        "child_ids": [],
    },
]

TIME_ENTRIES = [
    {
        "id": 8101,
        "project_id": 1,
        "issue_id": 101,
        "user_id": 2,
        "activity": {"id": 9, "name": "Development"},
        "hours": 3.5,
        "comments": "Implemented PKCE verifier handling.",
        "spent_on": "2026-02-12",
        "created_on": "2026-02-12T17:00:00Z",
        "updated_on": "2026-02-12T17:00:00Z",
    },
    {
        "id": 8102,
        "project_id": 1,
        "issue_id": 102,
        "user_id": 2,
        "activity": {"id": 10, "name": "QA"},
        "hours": 1.5,
        "comments": "Safari callback diagnostics.",
        "spent_on": "2026-02-14",
        "created_on": "2026-02-14T16:30:00Z",
        "updated_on": "2026-02-14T16:30:00Z",
    },
    {
        "id": 8201,
        "project_id": 2,
        "issue_id": 201,
        "user_id": 3,
        "activity": {"id": 9, "name": "Development"},
        "hours": 4.0,
        "comments": "Offline queue conflict resolution POC.",
        "spent_on": "2026-02-18",
        "created_on": "2026-02-18T18:00:00Z",
        "updated_on": "2026-02-18T18:00:00Z",
    },
]

WIKI_PAGES = [
    {
        "project_id": 1,
        "project_identifier": "platform-core",
        "title": "Feature-Login",
        "text": "Feature Login supports SSO, fallback local auth, and audit logging.",
        "version": 4,
        "author_id": 1,
        "comments": "Added audit logging details.",
        "updated_on": "2026-02-17T10:00:00Z",
        "parent": None,
    },
    {
        "project_id": 2,
        "project_identifier": "mobile-app",
        "title": "Offline-Sync",
        "text": "Offline sync uses local queue with conflict policy per entity type.",
        "version": 2,
        "author_id": 3,
        "comments": "Conflict policy update.",
        "updated_on": "2026-02-19T12:30:00Z",
        "parent": None,
    },
    {
        "project_id": 3,
        "project_identifier": "secret-lab",
        "title": "Biometric-Pilot",
        "text": "Restricted notes for biometric pilot rollout.",
        "version": 1,
        "author_id": 1,
        "comments": "Initial version.",
        "updated_on": "2026-02-18T12:00:00Z",
        "parent": None,
    },
]

NEWS = [
    {
        "id": 91001,
        "project_id": 1,
        "title": "Authentication hardening milestone",
        "summary": "Completed phase 1 hardening.",
        "description": "PKCE and token rotation controls are now in staging.",
        "author_id": 1,
        "created_on": "2026-02-15T08:00:00Z",
    },
    {
        "id": 91002,
        "project_id": 2,
        "title": "Offline sync RFC published",
        "summary": "RFC draft available.",
        "description": "Initial RFC for offline sync architecture is available.",
        "author_id": 2,
        "created_on": "2026-02-19T09:00:00Z",
    },
]

DOCUMENTS = [
    {
        "id": 92001,
        "project_id": 1,
        "category_id": 1,
        "title": "SSO rollout checklist",
        "description": "Checklist for rollout and rollback.",
        "created_on": "2026-02-13T09:00:00Z",
    },
    {
        "id": 92002,
        "project_id": 2,
        "category_id": 2,
        "title": "Offline sync design",
        "description": "Design proposal and edge case matrix.",
        "created_on": "2026-02-19T11:00:00Z",
    },
]

FILES = [
    {
        "id": 93001,
        "project_id": 1,
        "filename": "oauth-audit-template.xlsx",
        "filesize": 9100,
        "content_type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "description": "Audit sheet template",
        "content_url": "http://mock-redmine.local/files/93001/oauth-audit-template.xlsx",
        "author_id": 1,
        "created_on": "2026-02-14T12:00:00Z",
    }
]

BOARDS = [
    {
        "id": 94001,
        "project_id": 1,
        "name": "Platform Discussions",
        "description": "Architecture and operations discussions.",
        "position": 1,
        "topics_count": 2,
        "messages_count": 3,
    },
    {
        "id": 94002,
        "project_id": 3,
        "name": "Secret Discussions",
        "description": "Restricted board.",
        "position": 1,
        "topics_count": 1,
        "messages_count": 1,
    },
]

MESSAGES = [
    {
        "id": 95001,
        "board_id": 94001,
        "project_id": 1,
        "parent_id": None,
        "author_id": 1,
        "subject": "OAuth rollout readiness",
        "content": "Please review checklist and monitoring plan.",
        "replies_count": 1,
        "last_reply_id": 95002,
        "locked": False,
        "sticky": 1,
        "created_on": "2026-02-13T12:00:00Z",
        "updated_on": "2026-02-14T12:15:00Z",
    },
    {
        "id": 95002,
        "board_id": 94001,
        "project_id": 1,
        "parent_id": 95001,
        "author_id": 2,
        "subject": "Re: OAuth rollout readiness",
        "content": "Monitoring alerts added for callback errors.",
        "replies_count": 0,
        "last_reply_id": None,
        "locked": False,
        "sticky": 0,
        "created_on": "2026-02-14T12:15:00Z",
        "updated_on": "2026-02-14T12:15:00Z",
    },
    {
        "id": 95003,
        "board_id": 94001,
        "project_id": 1,
        "parent_id": None,
        "author_id": 3,
        "subject": "Safari callback errors",
        "content": "Collected browser logs and timings.",
        "replies_count": 0,
        "last_reply_id": None,
        "locked": False,
        "sticky": 0,
        "created_on": "2026-02-20T08:45:00Z",
        "updated_on": "2026-02-20T08:45:00Z",
    },
    {
        "id": 95999,
        "board_id": 94002,
        "project_id": 3,
        "parent_id": None,
        "author_id": 1,
        "subject": "Confidential pilot status",
        "content": "Restricted project status.",
        "replies_count": 0,
        "last_reply_id": None,
        "locked": True,
        "sticky": 1,
        "created_on": "2026-02-18T13:00:00Z",
        "updated_on": "2026-02-18T13:00:00Z",
    },
]
